export function index() {
  return [
    {
      pageProps: {
        user: {
          id: 0,
          loginId: null,
          nickName: null,
          doctorId: 0,
          sex: null,
          profileImage: null,
          level: 0,
          birthYear: 0,
          country: null,
          myHospitalDistrict: {},
          districts: [],
          phoneNational: null,
          agreeEmail: false,
          agreeMarketing: false,
          agreeSms: false,
          sendPushAd: false,
        },
        authorization: "152352ab7eaf432a88b2b504858ab6ad",
        keyword: "눈성형",
        treatmentCategoryName: "눈성형",
        treatmentCategoryId: 413,
        breadcrumb: [
          {
            text: "홈",
            href: "/",
          },
          {
            text: "눈성형",
            href: "/search?category=눈성형",
          },
        ],
        totalLength: 24014,
        eventTotalLength: 3766,
        communityDocumentTotalLength: 10000,
        hospitalTotalLength: 248,
        treatmentTotalLength: 0,
        reviewTotalLength: 10000,
        reviews: [],
        events: [
          {
            id: 6554,
            title: "팝 평생 자연유착 눈성형 쌍꺼풀 매몰",
            titleImage:
              "https://image2.gnsister.com/images/direct/1712302391867_312985ea4de14a46b0adc3fb91b871ec.jpg?originalImageWidth=1080&originalImageHeight=1080",
            treatmentList: [
              "쌍꺼풀(매몰)",
              "눈재수술",
              "쌍꺼풀(자연유착)",
              "윗트임",
              "앞트임",
              "밑트임",
              "뒤트임",
              "눈매교정",
            ],
            hospitalId: 370,
            hospitalSubwayCode: "SUB_S3_336",
            hospitalSubway: "압구정역",
            hospitalName: "팝성형외과의원",
            discountedCost: 419000,
            cost: 825000,
            currency: "KRW",
            discountRate: 49,
            rating: 9.4,
            ratingCount: 9414,
            type: "EVENT",
            vat: "INCLUDED",
            createTime: 1542660834000,
            assessmentState: "GROWTH",
            useBuyNow: false,
          },
          {
            id: 13600,
            title: "옐로우 토탈 눈성형 자연유착 매몰쌍꺼풀",
            titleImage:
              "https://image2.gnsister.com/images/direct/1711334369881_6e124cc64e8c451c871c5fdf60f73b93.jpg?originalImageWidth=1080&originalImageHeight=1080",
            treatmentList: [
              "쌍꺼풀(매몰)",
              "눈재수술",
              "쌍꺼풀(자연유착)",
              "쌍꺼풀(절개)",
              "윗트임",
              "앞트임",
              "뒤트임",
              "눈매교정",
            ],
            hospitalId: 2776,
            hospitalSubwayCode: "SUB_S2_222",
            hospitalSubway: "강남역",
            hospitalName: "옐로우성형외과",
            discountedCost: 529000,
            cost: 529000,
            currency: "KRW",
            discountRate: 0,
            rating: 9.8,
            ratingCount: 2866,
            type: "EVENT",
            vat: "INCLUDED",
            createTime: 1596066601000,
            assessmentState: "CERTIFIED",
            useBuyNow: false,
          },
          {
            id: 14691,
            title: "제스타 눈성형 ",
            titleImage:
              "https://image2.gnsister.com/images/direct/1679981505595_1b784cb8984e43eea68c994ffa57e612.jpg?originalImageWidth=1080&originalImageHeight=1080",
            treatmentList: ["쌍꺼풀(매몰)", "쌍꺼풀(절개)"],
            hospitalId: 352,
            hospitalSubwayCode: "SUB_S3_336,SUB_S3_337,SUB_B_1512",
            hospitalSubway: "압구정역",
            hospitalName: "제스타성형외과",
            discountedCost: 440000,
            cost: 440000,
            currency: "KRW",
            discountRate: 0,
            rating: 9.7,
            ratingCount: 323,
            type: "EVENT",
            vat: "INCLUDED",
            createTime: 1603139228000,
            assessmentState: "CERTIFIED",
            useBuyNow: false,
          },
          {
            id: 542,
            title: " 마블 눈성형",
            titleImage:
              "https://image2.gnsister.com/images/direct/1675311245934_562e20bbbc264dd29b5d007effe96450.jpg?originalImageWidth=1080&originalImageHeight=1080",
            treatmentList: [
              "쌍꺼풀(매몰)",
              "눈재수술",
              "쌍꺼풀(자연유착)",
              "쌍꺼풀(절개)",
            ],
            hospitalId: 141,
            hospitalSubwayCode: "SUB_S2_222,SUB_S9_925",
            hospitalSubway: "강남역",
            hospitalName: "마블성형외과",
            discountedCost: 649000,
            cost: 649000,
            currency: "KRW",
            discountRate: 0,
            rating: 9.2,
            ratingCount: 2156,
            type: "EVENT",
            vat: "INCLUDED",
            createTime: 1456078443000,
            assessmentState: "GROWTH",
            useBuyNow: false,
          },
          {
            id: 23150,
            title: "예쁨온 온에어  눈성형",
            titleImage:
              "https://image2.gnsister.com/images/direct/1661495880525_3e6072a59ddd490f8338734a2fb5779a.jpg?originalImageWidth=1080&originalImageHeight=1080",
            treatmentList: [
              "쌍꺼풀(매몰)",
              "눈재수술",
              "쌍꺼풀(자연유착)",
              "쌍꺼풀(절개)",
              "윗트임",
              "앞트임",
              "밑트임",
              "눈매교정",
            ],
            hospitalId: 3403,
            hospitalSubwayCode: "SUB_S2_222,SUB_S9_925",
            hospitalSubway: "강남역",
            hospitalName: "온에어성형외과의원",
            discountedCost: 539000,
            cost: 539000,
            currency: "KRW",
            discountRate: 0,
            rating: 9.9,
            ratingCount: 714,
            type: "EVENT",
            vat: "INCLUDED",
            createTime: 1631838779000,
            assessmentState: "CERTIFIED",
            useBuyNow: false,
          },
          {
            id: 57098,
            title: "윌비 눈성형",
            titleImage:
              "https://image2.gnsister.com/images/direct/1693903148553_185fdcbacb914f51b7043de089d50f3b.jpg?originalImageWidth=1080&originalImageHeight=1080",
            treatmentList: [
              "쌍꺼풀(매몰)",
              "눈재수술",
              "쌍꺼풀(자연유착)",
              "쌍꺼풀(절개)",
              "눈밑지방이식",
              "눈밑지방제거",
              "눈매교정",
              "눈밑지방재배치",
            ],
            hospitalId: 4920,
            hospitalSubwayCode: "SUB_S3_337",
            hospitalSubway: "신사역",
            hospitalName: "윌비성형외과의원",
            discountedCost: 649000,
            cost: 1290000,
            currency: "KRW",
            discountRate: 50,
            rating: 9.6,
            ratingCount: 561,
            type: "EVENT",
            vat: "INCLUDED",
            createTime: 1693931709000,
            assessmentState: "GROWTH",
            useBuyNow: false,
          },
        ],
        communityDocuments: [
          {
            id: 2722649,
            categoryId: 11,
            categoryName: "병원질문",
            writer: {
              id: 5032896,
              doctorId: null,
              profile:
                "https://image2.gnsister.com/images/member/profile/1513135488959_65b26532ee494877a051aff19efdb4cf.png",
              nickname: "스트레스성위염",
              level: 3,
              engagementType: null,
            },
            writerDoctorId: null,
            hasThumbUp: false,
            commentCount: 5,
            thumbUpCount: 0,
            viewCount: 4,
            createTime: "약 2시간 전",
            edited: true,
            title: "",
            contents:
              "친한 언니 간만에 만났는데 눈이 이상해요 \r\n일부러 속상할까봐 안물어봤는데 어쩌다 성형이야기 나오고 \r\n본인이 먼저 트임 했는데 망했다고 이야기 하더라구요 \r\n제 눈에도 보이긴 했는데 ㅠㅠ 말하기 뭐했는데 먼저 말해주길래 \r\n복원 추천 해줬어요 \r\n복원 본인도 생각중이라고 병원 알아보는 중이라고 하더라구요 \r\n시원 이브 알아봤다고 하던데 또 병원 어디 있을까요?",
            photos: [],
            lang: "ko",
            hasDoctorComment: false,
            translateResult: null,
          },
          {
            id: 2571073,
            categoryId: 1,
            categoryName: "자유수다",
            writer: {
              id: 5928793,
              doctorId: null,
              profile:
                "https://image2.gnsister.com/images/member/profile/1513135488959_4131ffc481d74b849460ec1ea11fd9d5.png",
              nickname: "쇼타의좛",
              level: 2,
              engagementType: null,
            },
            writerDoctorId: null,
            hasThumbUp: false,
            commentCount: 112,
            thumbUpCount: 20,
            viewCount: 938,
            createTime: "2024.02.29",
            edited: true,
            title: "",
            contents:
              "남자 첫 성형을 시작하려고 합니다ㅠ\r\n성형하면 좀 더 자존감이 높아질까 해서 시작하는거고 콤플렉스 때문에 하게 됐네요\r\n코는 송강님처럼 됐으면 좋겠고 눈은 서강준님,송강님 합친 중간 정도요ㅠ 남자다웠으면 좋겠어요\r\n친구가 눈,코는 한번에 해버리는게 편할거다 조언해줘서 알아봅니다\r\n시작이 어려워서 도움을 좀 받을까 합니다…\r\n지인 추천 받아서 마블성형외과 알아봤는데 원장님 경력이나 후기도 맘에 들어서 가보기로 했습니다 다른 곳들 살짝 봤을때 눈만 맘에 들거나 코만 맘에 들어서 결정하기 더 어렵네요. 조금 도와주시면 감사하겠습니다ㅠ",
            photos: [
              {
                url: "https://image2.gnsister.com/images/document/1709189430851_b859f1547d5d41759037b4e037d2de48.jpg?originalImageWidth=1062&originalImageHeight=1309",
              },
              {
                url: "https://image2.gnsister.com/images/document/1709189430797_d08544ae784b450681d42bee24cba8d1.jpg?originalImageWidth=670&originalImageHeight=868",
              },
            ],
            lang: "ko",
            hasDoctorComment: false,
            translateResult: null,
          },
          {
            id: 2553167,
            categoryId: 2,
            categoryName: "시술/수술 전 질문",
            writer: {
              id: 5856147,
              doctorId: null,
              profile:
                "https://image2.gnsister.com/images/member/profile/1513135488959_818153a742fc4adf8cecc95fc44c4d6e.png",
              nickname: "려거고기",
              level: 2,
              engagementType: null,
            },
            writerDoctorId: null,
            hasThumbUp: false,
            commentCount: 87,
            thumbUpCount: 13,
            viewCount: 1803,
            createTime: "2024.02.20",
            edited: true,
            title: "",
            contents:
              "드레스성형외과의원에서 자연유착이랑 사선트임 듀얼트임 했어요\r\n\r\n눈이 꼬막눈처럼 답답해보이면서 소세지처럼 쌍꺼풀라인이 두꺼운게 스트레스였어요\r\n그래서 쌍꺼풀수술 하는 병원들 열심히 손품 발품 팔면서 쌍수후기들 찾아보다가\r\n가장 제 스타일 눈성형 케이스가 많았던 ㄷㄹㅅ에서 최종 결정 했습니다\r\n\r\n눈매교정까지는 굳이 필요 없을 것 같다고 권하시지 않으셨고\r\n제 취향을 말씀 안드렸는데도 세미아웃이 잘 어울릴 것 같다고\r\n예쁘게 라인 잡아주시면서 추천해주셨어요!♡♡\r\n\r\n또 몽고주름 때문에 눈이 답답해 보이는거라며 트임을 하면\r\n훨씬 이미지 개선이 될거라고 말씀해주셨어요\r\n쌍트라 붓기랑 흉터 걱정 많았는데 대략 2주만에 회복도 엄청 빠르게 되고\r\n실밥도 깔끔하게 제거해주셔서 흉터도 거의 없이 지금 너무 대대대대만족입니다!\r\n앞으로도 눈재수술 고민 없이 눈재수술 후기 찾아볼 일 없을 것 같아요 ㅎㅎㅎㅎ\r\n입술필러도 유명하던데 언제 기회되면 해보려구용",
            photos: [
              {
                url: "https://image2.gnsister.com/images/document/1708411401212_b340f40edb474559a9cc05b6755c5dac.jpg?originalImageWidth=1080&originalImageHeight=631",
              },
              {
                url: "https://image2.gnsister.com/images/document/1708411401251_4fc08cdab0e34e0aab2d44d9f05017ce.jpg?originalImageWidth=1080&originalImageHeight=666",
              },
              {
                url: "https://image2.gnsister.com/images/document/1708411401350_1f1b447d43f147cab58c416781e06331.jpg?originalImageWidth=1080&originalImageHeight=666",
              },
              {
                url: "https://image2.gnsister.com/images/document/1708411401442_3eb3bc38db39441c99561a9f84ea632d.jpg?originalImageWidth=1080&originalImageHeight=665",
              },
            ],
            lang: "ko",
            hasDoctorComment: false,
            translateResult: null,
          },
        ],
        hospitals: [
          {
            id: 370,
            name: "팝성형외과의원",
            mainImage:
              "https://image2.gnsister.com/images/direct/1678167128052_6e4daae119b846e98ac9da648f98e5b9.jpg?originalImageWidth=600&originalImageHeight=240",
            rating: 9.4,
            ratingCount: 9974,
            reviewCount: 41110,
            supportingLangList: ["ja"],
            isCertified: false,
            assessmentState: "GROWTH",
            photos: [],
            sido: "서울",
            pageCount: 25,
          },
          {
            id: 938,
            name: "나나성형외과의원",
            mainImage:
              "https://image2.gnsister.com/images/direct/1677820120807_7329b9dcdc5746de8c5e01b9dbcc97bb.jpg?originalImageWidth=600&originalImageHeight=240",
            rating: 9.6,
            ratingCount: 15017,
            reviewCount: 39398,
            supportingLangList: ["ja"],
            isCertified: false,
            assessmentState: "GROWTH",
            photos: [],
            sido: "서울",
            pageCount: 72,
          },
          {
            id: 250,
            name: "디에이성형외과의원",
            mainImage:
              "https://image2.gnsister.com/images/hospital/1515034360262_edcd481595034a08a0190a2c3cf7a517.jpg",
            rating: 9.4,
            ratingCount: 8788,
            reviewCount: 32504,
            supportingLangList: ["ja"],
            isCertified: false,
            assessmentState: "GROWTH",
            photos: [],
            sido: "서울",
            pageCount: 81,
          },
        ],
        treatments: [],
        language: "ko-KR",
        token: "152352ab7eaf432a88b2b504858ab6ad",
        blogs: null,
        blogTotalLength: null,
        title: "'눈성형'에 대한 검색결과 24014개 | 강남언니",
        meta: {
          description:
            "국내 1위 성형정보앱 강남언니. 리얼후기부터 가격비교, 상담예약까지 한번에. 강남언니를 지금 만나보세요.",
          image: "https://www.gangnamunni.com/images/kr/meta_thumb_02.jpg",
          locale: "ko_KR",
          name: "강남언니",
          title: "'눈성형'에 대한 검색결과 24014개 | 강남언니",
          twtCardType: "summary_large_image",
          type: "website",
          desc: "'눈성형'을 전문으로 하는 병원과 이벤트를 확인해보세요!",
        },
      },
      __N_SSP: true,
    },
  ];
}
